[package]
name = "sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
taskctx = { git = "ssh://git@github.com/shilei-massclouds/taskctx.git" }
run_queue = { git = "ssh://git@github.com/shilei-massclouds/run_queue.git" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc.git" }
axconfig = { git = "ssh://git@github.com/shilei-massclouds/axconfig.git" }
axtype = { git = "ssh://git@github.com/shilei-massclouds/axtype.git" }
axerrno = { git = "ssh://git@github.com/shilei-massclouds/axerrno.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal.git" }
task = { git = "ssh://git@github.com/shilei-massclouds/task.git" }
